name: CI

on:
- push
- pull_request

jobs:
  check:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven Wrapper
      run: |
        ./mvnw -B package
    - name: Build Docker image and push it to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ github.token }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/prometheus-jdbc-exporter
        tag_with_ref: true
